export const MANDAL_REQUEST = 'MANDAL_REQUEST'
export const MANDAL_SUCCESS = 'MANDAL_SUCCESS'
export const MANDAL_FAILURE = 'MANDAL_FAILURE'

export const UPDATE_MANDAL_REQUEST = 'UPDATE_MANDAL_REQUEST'
export const UPDATE_MANDAL_SUCCESS = 'UPDATE_MANDAL_SUCCESS'
export const UPDATE_MANDAL_FAILURE = 'UPDATE_MANDAL_FAILURE'
